export const types = {
  USER : {
    REGISTER_STEP_ONE: {
      CREATE: "USER_REGISTER_STEP_ONE_CREATE",
      UPDATE: "USER_REGISTER_STEP_ONE_UPDATE",
      VIEW: "USER_REGISTER_STEP_ONE_VIEW",
      FETCHING: "USER_REGISTER_STEP_ONE_FETCHING",
      TRANSMITTING: "USER_REGISTER_STEP_ONE_TRANSMITTING",
      CANCELFETCHING: "USER_REGISTER_STEP_ONE_CANCELFETCHING",
      UPDATING: "USER_REGISTER_STEP_ONE_UPDATING"
    },
    LOGIN: {

    }
  },
  TRANSACTION:{
    BUY:{

    }
  },
  WISE_MESSAGE: {
    ADD: "ADD_WISE_MESSAGE",
    CLEAR: "CLEAR_WISE_MESSAGE",
  }
};
